data:
  type: cell
  source: ctrl
  condition: condition 
  path: datasets/scrna-norman/norman_2019_data_hvg.h5ad

datasplit:
  groupby: condition 
  name: train_test
  test_size: 0.2
  random_state: 0

dataloader:
  batch_size: 256
  shuffle: true

model:
  embedding:
    path: datasets/scrna-norman/perturbation_embedding_norm.h5
